# Generated by Django 2.2 on 2020-06-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=30)),
                ('comuna', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('categori', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empresita.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('fecha', models.DateField()),
                ('monto_final', models.IntegerField(null=True)),
                ('descuento', models.IntegerField(null=True)),
                ('produc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empresita.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('web', models.CharField(max_length=30)),
                ('rut', models.IntegerField(unique=True)),
                ('direc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empresita.Direccion')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empresita.Proveedor'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('direc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empresita.Direccion')),
                ('venta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Empresita.Venta')),
            ],
        ),
    ]
