# Generated by Django 2.2 on 2020-06-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='monto_final',
        ),
    ]
