# Generated by Django 2.2 on 2020-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresita', '0003_auto_20200701_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_final',
            field=models.FloatField(null=True),
        ),
    ]
