# Generated by Django 2.2 on 2020-07-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresita', '0004_venta_monto_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.BooleanField(null=True),
        ),
    ]
